#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Reinstalling dependencies..."

ynh_nodejs_install

#=================================================
# RESTORE THE APP MAIN DIR AND ITS DATA
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

ynh_restore "$data_dir"

chown -R "$app:$app" "$install_dir"
chown -R "$app:$app" "$data_dir"
chmod 700 "$data_dir"
chmod 600 "$install_dir/.env"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "$app" --description="Web SQL client for 16 database engines" --log="/var/log/$app/$app.log"

ynh_restore "/etc/logrotate.d/$app"

ynh_restore "/var/log/$app/"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="/var/log/$app/$app.log" --wait_until="LibreDB Studio"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
